import IconButton, { Icon } from "../../components/basic/IconButton"
import Loader from "../../components/Loader"
import { Children } from "../../framework/createElement"
import { PageComponent } from "../../framework/PageComponent"
import AnkiConnect, { NoteBase } from "../../utils/AnkiConnect"
import { UnicodeCharacterType, unicodeType } from "../../utils/AnkiUtil"
import { serverPostJson } from "../../utils/Audio"
import { getSetting } from "../../views/SettingsModal"
import { getAnkiWords } from "../anki/CardList"

const deckName = "Mining Helper Kanji"

export default class KanjiPage extends PageComponent {
    Id = "kanji-page"
    override Title = "Mining Helper - Kanji"
    Node: Children
    constructor() {
        super()
        this.Node = <Loader load={main} showFullError />
    }
}


const main = async () => {
    const kanjiDeck = await AnkiConnect.call("deckNames", undefined)
    if (!kanjiDeck.includes(deckName)) throw `Deck named '${deckName}' not found`

    const kanjiNotes = await AnkiConnect.call("notesInfo", { query: `deck:\"${deckName}\"` })

    const vocabDeckName = await getSetting("targetAnkiDeck")

    const knownKanji = new Set<string>()
    for (const note of kanjiNotes) {
        const kanji = note.fields["Kanji"]?.value
        if (!kanji) throw `${note.noteId} missing 'Kanji' field`
        knownKanji.add(kanji)
    }

    const vocab = await getAnkiWords()
    let knownKanjiUsages = 0
    let unknownKanjiUsages = 0
    let vocabKanji = new Set<string>()

    let unknownKanjiUsageMap = new Map<string, number>()

    for (const word of vocab) {
        for (let i = 0; i < word.length; i++) {
            const c = word[i]
            if (unicodeType(c) === UnicodeCharacterType.Kanji) {
                if (knownKanji.has(c)) knownKanjiUsages += 1
                else {
                    unknownKanjiUsages += 1
                    const cur = unknownKanjiUsageMap.get(c) ?? 0
                    unknownKanjiUsageMap.set(c, cur + 1)
                }
                vocabKanji.add(c)
            }
        }
    }

    const recommendedKanji = [...unknownKanjiUsageMap.entries()].sort((a, b) => b[1] - a[1]).slice(0, 10);
    const refreshInput = <input autocomplete="off" id="search" placeholder="Update" /> as HTMLInputElement


    return <div id="inner-body">
        <div id="refresh-container">
            {refreshInput}
            <IconButton icon="refresh" onClick={() => refresh(refreshInput.value)}
                tooltip={"Updates the note for the supplied input kanji.\nResets modifications to the autogenerated fields.\nReview history and custom field are unaffected."} />
        </div>
        <div id="stats">
            <div>Vocab loaded: {vocab.length}
                <Icon icon="help" tooltip="Can refresh this from the Anki page"
                    component="a" componentProps={{ href: "/anki.html" }} />
            </div>
            <div>Kanji notes found: {kanjiNotes.length}</div>
            <div>Unique kanji in vocab: {vocabKanji.size}</div>
            <div>Known kanji usages in vocab: {knownKanjiUsages}</div>
            <div>Unknown kanji usages in vocab: {unknownKanjiUsages}</div>
        </div>
        <hr />
        <div id="recommended-kanji">
            <h4>Recommended Kanji</h4>
            {recommendedKanji.map(e => <div>
                <a href={`https://jisho.org/search/${encodeURIComponent(`${e[0]} #kanji`)}`}
                    tooltip="View on jisho"
                    rel="noopener noreferrer" target="_blank">j</a>
                <a href={`https://jpdb.io/kanji/${encodeURIComponent(e[0])}`}
                    tooltip="View on jpdb"
                    rel="noopener noreferrer" target="_blank">d</a>
                {/* TODO pressing this should remove this row (and maybe add a new one) */}
                <IconButton icon="add" onClick={() => createKanjiCard(e[0])} tooltip="Add to Kanji deck" />
                <span>{e[0]} - <span className="link-button"
                    onclick={() => AnkiConnect.call("guiBrowse", { query: `deck:\"${vocabDeckName}\" word:*${e[0]}*` })}>
                    {e[1]} usages
                </span></span>
            </div>)}
        </div>
    </div>
}

async function getNoteInfo(kanji: string): Promise<NoteBase> {
    // TODO this assumes some fields in the vocab deck when we could be pulling those from settings

    const res = await serverPostJson<KanjiInfo>(`kanji-info:${kanji}`)
    const vocabDeckName = await getSetting("targetAnkiDeck")

    const knownCardIds = await AnkiConnect.call("findCards", { query: `deck:\"${vocabDeckName}\" word:*${kanji}*` })
    const intervals = await AnkiConnect.call("getIntervals", { cards: knownCardIds })
    // sorts based on longest intervals first
    // could eventually try getting more variety, ie. trading harder words for varied readings
    // sorting by longest interval could lead to skipping the harder (even if they're common) readings
    const zipped = knownCardIds.map((e, i) => [e, intervals[i]]).sort((a, b) => b[1] - a[1])
    const top5 = zipped.slice(0, 5).map(e => e[0])
    const noteIds = await AnkiConnect.call("cardsToNotes", { cards: top5 })
    const noteInfo = await AnkiConnect.call("notesInfo", { notes: noteIds })
    const simpleKnownWordInfo = noteInfo.map(e => {
        const furigana = e.fields["Word Furigana"]?.value
        const meaning = e.fields["Word Meaning"]?.value
        return `${furigana} - ${meaning}`
    })

    return {
        fields: {
            Kanji: res.Kanji,
            Meaning: res.Meanings.join(", "),
            Radical: res.Radical.Kanji + " - " + res.Radical.Meaning,
            // we use <br> for line breaks so it renders a bit better in Anki browser
            // on the actual card rendering side, we'll split out the <br> anyways
            Parts: res.Parts?.map(e => e.Meaning ? e.Part + " - " + e.Meaning : e.Part).join("<br>"),
            ["Kun Readings"]: res.KunReadings.join(", "),
            ["On Readings"]: res.OnReadings.join(", "),
            ["Name Readings"]: res.NameReadings.join(", "),
            ["Examples"]: simpleKnownWordInfo.join("<br>")
            // Variants: , // don't think we really needs these for now
        },
    }
}

async function createKanjiCard(kanji: string) {
    return AnkiConnect.call("addNote", {
        note: {
            ...await getNoteInfo(kanji),
            deckName, modelName: deckName
        }
    })
}

async function refresh(kanji: string) {
    if (!kanji) return
    const notes = await AnkiConnect.call("findNotes", { query: `"deck:${deckName}" kanji:${kanji}` })
    if (notes.length === 0) throw new Error(`No notes matching ${kanji}`)
    if (notes.length > 1) throw new Error(`Multiple notes matching ${kanji}`)
    return AnkiConnect.call("updateNote", {
        note: {
            ...await getNoteInfo(kanji),
            id: notes[0]
        }
    })
}

interface KanjiInfo {
    Kanji: string
    Parts?: {
        Part: string
        Meaning: string
    }[]
    StrokeCount: number
    Radical: {
        Kanji: string
        Meaning: string
    }
    Meanings: string[]
    KunReadings: string[]
    OnReadings: string[]
    NameReadings: string[]
}
