import IconButton, { Icon } from "../../components/basic/IconButton"
import Loader from "../../components/Loader"
import { AnkiFieldInfo, AnkiFieldKey, getSetting } from "../../core/Settings"
import { Children } from "../../framework/createElement"
import { PageComponent } from "../../framework/PageComponent"
import AnkiConnect, { AnkiNote, NoteBase } from "../../utils/AnkiConnect"
import { UnicodeCharacterType, unicodeType } from "../../utils/AnkiUtil"
import { serverPostJson } from "../../utils/Audio"
import { addKnownAnkiKanji, reloadAnkiKanjiSet } from "../../utils/KanjiSet"
import { getAnkiNoteKeys } from "../anki/CardList"

const deckName = "Mining Helper Kanji"

export default class KanjiPage extends PageComponent {
    Id = "kanji-page"
    override Title = "Mining Helper - Kanji"
    Node: Children
    constructor() {
        super()
        this.Node = <Loader load={main} showFullError />
    }
}


const main = async () => {
    const kanjiDeck = await AnkiConnect.call("deckNames", undefined)
    if (!kanjiDeck.includes(deckName)) throw `Deck named '${deckName}' not found`

    const kanjiNotes = await AnkiConnect.call("notesInfo", { query: `deck:\"${deckName}\"` })

    const vocabDeckName = await getSetting("ankiVocabDeck")

    const knownKanji = new Set<string>()
    for (const note of kanjiNotes) {
        const kanji = note.fields["Kanji"]?.value
        if (!kanji) throw `${note.noteId} missing 'Kanji' field`
        knownKanji.add(kanji)
    }

    const vocab = await getAnkiNoteKeys()
    let knownKanjiUsages = 0
    let unknownKanjiUsages = 0
    let vocabKanji = new Set<string>()

    let unknownKanjiUsageMap = new Map<string, number>()

    for (const word of vocab) {
        for (let i = 0; i < word.length; i++) {
            const c = word[i]
            if (unicodeType(c) === UnicodeCharacterType.Kanji) {
                if (knownKanji.has(c)) knownKanjiUsages += 1
                else {
                    unknownKanjiUsages += 1
                    const cur = unknownKanjiUsageMap.get(c) ?? 0
                    unknownKanjiUsageMap.set(c, cur + 1)
                }
                vocabKanji.add(c)
            }
        }
    }

    const sortedKanjiUsage = [...unknownKanjiUsageMap.entries()].sort((a, b) => b[1] - a[1])
    const recommendedKanji = sortedKanjiUsage.slice(0, 10);
    const refreshInput = <input autocomplete="off" id="search" placeholder="Update" /> as HTMLInputElement

    const unknownKanjiWith5Usage = sortedKanjiUsage.reduce((p, c) => p + (c[1] >= 5 ? 1 : 0), 0)

    return <div id="inner-body">
        <div id="refresh-container">
            {refreshInput}
            <IconButton icon="refresh" onClick={async () => {
                await reloadAnkiKanjiSet() // TODO move this once we set up settings for this
                updateKanjiNote(refreshInput.value)
            }}
                tooltip={"Updates the note for the supplied input kanji.\nResets modifications to the autogenerated fields.\nReview history and custom field are unaffected."} />
        </div>
        <div id="stats">
            <div>Vocab loaded: {vocab.length}
                <Icon icon="help" tooltip="Can refresh this from the Anki page"
                    component="a" componentProps={{ href: "/anki.html" }} />
            </div>
            <div>Kanji notes found: {kanjiNotes.length}</div>
            <div>Unique kanji in vocab: {vocabKanji.size}</div>
            <div>Known kanji usages in vocab: {knownKanjiUsages}</div>
            <div>Unknown kanji usages in vocab: {unknownKanjiUsages}</div>
            <div>Unknown kanji with 5+ usages: {unknownKanjiWith5Usage}</div>
        </div>
        <hr />
        <div id="recommended-kanji">
            <h4>Recommended Kanji</h4>
            {recommendedKanji.map(e => <div>
                <a href={`https://jisho.org/search/${encodeURIComponent(`${e[0]} #kanji`)}`}
                    tooltip="View on jisho"
                    rel="noopener noreferrer" target="_blank">j</a>
                <a href={`https://jpdb.io/kanji/${encodeURIComponent(e[0])}`}
                    tooltip="View on jpdb"
                    rel="noopener noreferrer" target="_blank">d</a>
                {/* TODO pressing this should remove this row (and maybe add a new one) */}
                <IconButton icon="add" onClick={() => createKanjiCard(e[0])} tooltip="Add to Kanji deck" />
                <span>{e[0]} - <span className="link-button"
                    onclick={() => AnkiConnect.call("guiBrowse", { query: `deck:\"${vocabDeckName}\" word:*${e[0]}*` })}>
                    {e[1]} usages
                </span></span>
            </div>)}
        </div>
    </div>
}

async function getNoteInfo(kanji: string): Promise<NoteBase> {
    const res = await serverPostJson<KanjiInfo>(`kanji-info:${kanji}`)
    const vocabDeckName = await getSetting("ankiVocabDeck")

    const ankiFields = await getSetting("ankiFields")
    function fieldName(key: AnkiFieldKey) {
        return ankiFields[key] ?? AnkiFieldInfo[key].name
    }

    const cardIds = await AnkiConnect.call("findCards", { query: `deck:\"${vocabDeckName}\" ${fieldName("word")}:*${kanji}*` })
    const noteIds = await AnkiConnect.call("cardsToNotes", { cards: cardIds })
    const noteInfo = await AnkiConnect.call("notesInfo", { notes: noteIds })
    const intervals = await AnkiConnect.call("getIntervals", { cards: cardIds })

    const sortInfo = noteInfo.map((e, i) => {
        let kanjiCount = 0
        let hasKana = false
        const kanji = e.fields[fieldName("word")]!.value
        for (let i = 0; i < kanji.length; i++) {
            const type = unicodeType(kanji, i)
            if (type === UnicodeCharacterType.Kanji)
                kanjiCount += 1
            else if (type === UnicodeCharacterType.Kana)
                hasKana = true

        }
        // when there's multiple kanji, we don't really care if it has kana or not
        // 1 kanji no kana = 0
        // 1 kanji has kana = 1
        // multiple kanji = 2
        return [kanjiCount > 1 ? 2 : hasKana ? 1 : 0, intervals[i]] as const
    })
    const sortedNotesIndices: number[] = []
    for (let i = 0; i < noteInfo.length; i++)
        sortedNotesIndices.push(i)
    sortedNotesIndices.sort((ai, bi) => {
        const a = sortInfo[ai]
        const b = sortInfo[bi]
        // 2nd one is intentionally inverted
        return (a[0] - b[0] || b[1] - a[1])
    })
    return noteInfoToKanjiNote(kanji, sortedNotesIndices.map(e => noteInfo[e]), res)
}

// TODO this method doesn't actually use notesWithIntervals, it really needs sortedNotes
// This method shouldn't do anything expensive (network calls, large filters) so it can be bulk called
function noteInfoToKanjiNote(kanji: string, sortedNotes: AnkiNote[], kanjiInfo: KanjiInfo): NoteBase {
    // these should be all different readings, if there's <5, it will pull whatever has the best interval
    // TODO this assumes some fields in the vocab deck when we could be pulling those from settings
    const examples: AnkiNote[] = []

    const foundReadings = new Set<string>()
    for (const note of sortedNotes) {
        const furigana = note.fields["Word Furigana"]?.value
        if (furigana) {
            const reading = getReadingFor(kanji, furigana)
            if (reading) {
                if (!foundReadings.has(reading)) {
                    foundReadings.add(reading)
                    examples.push(note)
                }
            }
        }
    }
    for (const note of sortedNotes) {
        if (examples.length >= 5) break
        if (!examples.includes(note)) examples.push(note)
    }

    const simpleExamples = examples.map(e => {
        const furigana = e.fields["Word Furigana"]?.value
        const meaning = e.fields["Word Meaning"]?.value
        return `${furigana} - ${meaning}`
    })

    return {
        fields: {
            Kanji: kanjiInfo.Kanji,
            Meaning: kanjiInfo.Meanings.join(", "),
            Radical: kanjiInfo.Radical.Kanji + " - " + kanjiInfo.Radical.Meaning,
            // we use <br> for line breaks so it renders a bit better in Anki browser
            // on the actual card rendering side, we'll split out the <br> anyways
            Parts: kanjiInfo.Parts?.map(e => e.Meaning ? e.Part + " - " + e.Meaning : e.Part).join("<br>"),
            ["Kun Readings"]: kanjiInfo.KunReadings.join(", "),
            ["On Readings"]: kanjiInfo.OnReadings.join(", "),
            ["Name Readings"]: kanjiInfo.NameReadings.join(", "),
            ["Examples"]: simpleExamples.join("<br>")
            // Variants: , // don't think we really needs these for now
        },
    }
}

async function updateAllKanjiNotes() {
    // This is really slow, could definitely speed it up like 100x
    const kanjiNotes = await AnkiConnect.call("notesInfo", { query: `deck:\"${deckName}\"` })
    for (const note of kanjiNotes) {
        await updateKanjiNote(note.fields["Kanji"]!.value)
    }
}

async function createKanjiCard(kanji: string) {
    await AnkiConnect.call("addNote", {
        note: {
            ...await getNoteInfo(kanji),
            deckName, modelName: deckName
        }
    })
    await addKnownAnkiKanji(kanji)
}

async function updateKanjiNote(kanji: string) {
    if (kanji === "ALL KANJI") return updateAllKanjiNotes()
    if (!kanji) return
    const notes = await AnkiConnect.call("findNotes", { query: `"deck:${deckName}" kanji:${kanji}` })
    if (notes.length === 0) throw new Error(`No notes matching ${kanji}`)
    if (notes.length > 1) throw new Error(`Multiple notes matching ${kanji}`)
    return AnkiConnect.call("updateNote", {
        note: {
            ...await getNoteInfo(kanji),
            id: notes[0]
        }
    })
}

interface KanjiInfo {
    Kanji: string
    Parts?: {
        Part: string
        Meaning: string
    }[]
    StrokeCount: number
    Radical: {
        Kanji: string
        Meaning: string
    }
    Meanings: string[]
    KunReadings: string[]
    OnReadings: string[]
    NameReadings: string[]
}


function getReadingFor(kanji: string, furigana: string) {
    let o = ""
    let target = ""
    let inside = false
    for (let i = 0; i < furigana.length; i++) {
        const c = furigana[i]
        if (inside) {
            if (c === "]") return o
            o += furigana[i]
        } else if (c === "[" && target === kanji) inside = true
        else {
            const type = unicodeType(c)
            if (type === UnicodeCharacterType.Kanji || type === UnicodeCharacterType.Kana) target += c
            else target = ""
        }
    }
}