name: Deploy Web

on:
  push:
    branches:
    - main
    paths:
    - src/**
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v6
      - uses: dw-labs-org/dart-sass-gha@v1

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Build
        run: |
          npm i
          node esbuild.mjs --prod --gh-pages
          sass src/main.scss:dist/main.css

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'dist'

          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  